# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12EdW56EIwzbACKJCs1CYyDaqVv-zWq7g
"""

# ═══════════════════════════════════════════════════════════════
#  HINDI OCR — MODEL RESTORE  (single cell, paste into new .ipynb)
# ═══════════════════════════════════════════════════════════════
import subprocess, sys, os, shutil

subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                "huggingface_hub", "editdistance", "psutil"], check=True)

import tensorflow as tf
print(f"TensorFlow: {tf.__version__}")
print(f"GPU: {tf.config.list_physical_devices('GPU')}")

tf.compat.v1.disable_eager_execution()

# ── 1. Download from HuggingFace ────────────────────────────────
from huggingface_hub import hf_hub_download

REPO_ID   = "rajesh-1902/hindi-crnn-ctc-sentence-model"
MODEL_DIR = "/content/model_hindi"   # absolute everywhere
CODE_DIR  = "/content"
os.makedirs(MODEL_DIR, exist_ok=True)

print("\n📥 Downloading model weights (snapshot-5)...")
for hf_path in [
    "model/charList.txt",
    "model/corpus.txt",
    "model/accuracy.txt",
    "model/snapshot-5.data-00000-of-00001",
    "model/snapshot-5.index",
    "model/snapshot-5.meta",
]:
    local = hf_hub_download(repo_id=REPO_ID, filename=hf_path, repo_type="model")
    shutil.copy2(local, os.path.join(MODEL_DIR, os.path.basename(hf_path)))
    print(f"  ✅ {os.path.basename(hf_path)}")

print("\n📥 Downloading code files...")
for hf_path in [
    "code/Model_Hindi.py",
    "code/DataLoader_Hindi.py",
    "code/SamplePreprocessor_Hindi.py",
    "code/main_hindi.py",
    "code/build_charlist_hindi.py",
]:
    local = hf_hub_download(repo_id=REPO_ID, filename=hf_path, repo_type="model")
    shutil.copy2(local, os.path.join(CODE_DIR, os.path.basename(hf_path)))
    print(f"  ✅ {os.path.basename(hf_path)}")

# ── 2. Write checkpoint with ABSOLUTE path (prevents double-prefix bug) ──
SNAPSHOT = f"{MODEL_DIR}/snapshot-5"   # e.g. /content/model_hindi/snapshot-5
with open(os.path.join(MODEL_DIR, "checkpoint"), "w") as f:
    f.write(f'model_checkpoint_path: "{SNAPSHOT}"\n')
    f.write(f'all_model_checkpoint_paths: "{SNAPSHOT}"\n')
print(f"\n✅ checkpoint → {SNAPSHOT}")

# ── 3. Fix known bugs in Model_Hindi.py ─────────────────────────
model_py = os.path.join(CODE_DIR, "Model_Hindi.py")
with open(model_py, "r") as f:
    src = f.read()
src = src.replace("tv.initialized_value()", "tv")   # removed in TF2
src = src.replace("../model_hindi/", "model_hindi/")
with open(model_py, "w") as f:
    f.write(src)

for fname in ["main_hindi.py"]:
    fp = os.path.join(CODE_DIR, fname)
    with open(fp, "r") as f: c = f.read()
    c = c.replace("../model_hindi/", "model_hindi/")
    with open(fp, "w") as f: f.write(c)

print("✅ Bug fixes applied")

# ── 4. Load model ────────────────────────────────────────────────
import cv2, numpy as np
sys.path.insert(0, CODE_DIR)
os.chdir(CODE_DIR)

for mod in ["Model_Hindi", "SamplePreprocessor_Hindi", "DataLoader_Hindi"]:
    sys.modules.pop(mod, None)

from Model_Hindi import Model, DecoderType
from SamplePreprocessor_Hindi import preprocess

with open(os.path.join(MODEL_DIR, "charList.txt"), "r", encoding="utf-8") as f:
    charList = f.read()
print(f"\nCharacter set: {len(charList)} chars")

model = Model(charList, DecoderType.BestPath, mustRestore=True)
print("\n✅ Model restored from snapshot-5 — ready for inference!")

# ── 5. Inference helper ──────────────────────────────────────────
class _Batch:
    def __init__(self, imgs): self.imgs = imgs

def recognize(image_path: str) -> str:
    """Run Hindi OCR on a single greyscale image file. Returns predicted text."""
    img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        raise FileNotFoundError(f"Cannot read: {image_path}")
    img_proc = preprocess(img, Model.imgSize)
    batch    = np.expand_dims(img_proc, axis=0)
    return model.inferBatch(_Batch(batch))[0]

print("\n💡 Usage:")
print("   text = recognize('/path/to/hindi_line.png')")
print("   print(text)")

# ── FIX CELL: reset graph state, then restore cleanly ───────────
import tensorflow as tf
import os, sys, cv2, numpy as np

# THIS is the root fix — wipe all previously created variables
tf.compat.v1.reset_default_graph()
tf.compat.v1.disable_eager_execution()   # must re-apply after reset

MODEL_DIR = "/content/model_hindi"
CODE_DIR  = "/content"
os.chdir(CODE_DIR)

# Force fresh import (stale module may carry old graph references)
for mod in ["Model_Hindi", "SamplePreprocessor_Hindi", "DataLoader_Hindi"]:
    sys.modules.pop(mod, None)

from Model_Hindi import Model, DecoderType
from SamplePreprocessor_Hindi import preprocess

with open(f"{MODEL_DIR}/charList.txt", "r", encoding="utf-8") as f:
    charList = f.read()

# Build graph exactly once → names will be clean, no _N suffixes
model = Model(charList, DecoderType.BestPath, mustRestore=True)
print("\n✅ Model restored successfully!")

# ── Inference helper ─────────────────────────────────────────────
class _Batch:
    def __init__(self, imgs): self.imgs = imgs

def recognize(image_path: str) -> str:
    img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        raise FileNotFoundError(f"Cannot read: {image_path}")
    img_proc = preprocess(img, Model.imgSize)
    return model.inferBatch(_Batch(np.expand_dims(img_proc, axis=0)))[0]

print("💡 Usage: text = recognize('/path/to/hindi_line.png')")

# ── FINAL FIX CELL ───────────────────────────────────────────────
import tensorflow as tf
import os, sys, cv2, numpy as np

# clear_session() resets BOTH TF graph AND Keras layer name counters.
# disable_eager must come AFTER clear_session (clear_session re-enables eager).
tf.keras.backend.clear_session()
tf.compat.v1.disable_eager_execution()
# No reset_default_graph() needed — clear_session already did it internally.

MODEL_DIR = "/content/model_hindi"
CODE_DIR  = "/content"
os.chdir(CODE_DIR)

for mod in ["Model_Hindi", "SamplePreprocessor_Hindi", "DataLoader_Hindi"]:
    sys.modules.pop(mod, None)

from Model_Hindi import Model, DecoderType
from SamplePreprocessor_Hindi import preprocess

with open(f"{MODEL_DIR}/charList.txt", "r", encoding="utf-8") as f:
    charList = f.read()

model = Model(charList, DecoderType.BestPath, mustRestore=True)
print("\n✅ Model restored successfully!")

# ── Inference helper ─────────────────────────────────────────────
class _Batch:
    def __init__(self, imgs): self.imgs = imgs

def recognize(image_path: str) -> str:
    img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        raise FileNotFoundError(f"Cannot read: {image_path}")
    img_proc = preprocess(img, Model.imgSize)
    return model.inferBatch(_Batch(np.expand_dims(img_proc, axis=0)))[0]

print("💡 Usage: text = recognize('/path/to/hindi_line.png')")

from datasets import load_dataset

# Load your dataset
dataset = load_dataset("rajesh-1902/hindi-ocr-dataset")

# Inspect structure
print(dataset)
print(dataset["train"][0])

# ── EVALUATION CELL ──────────────────────────────────────────────
import numpy as np
import editdistance
from tqdm.auto import tqdm

# ── Config ───────────────────────────────────────────────────────
SPLIT      = "test"       # "train", "validation", or "test"
MAX_ITEMS  = None         # set to e.g. 500 for a quick run; None = full split
BATCH_SIZE = 16           # images per inference batch

eval_data = dataset[SPLIT]
if MAX_ITEMS:
    eval_data = eval_data.select(range(MAX_ITEMS))

total = len(eval_data)
print(f"Evaluating on {total} samples from '{SPLIT}' split...\n")

# ── Helpers ──────────────────────────────────────────────────────
class _Batch:
    def __init__(self, imgs): self.imgs = imgs

def pil_to_model_input(pil_img):
    """PIL RGB → greyscale numpy → model-preprocessed array."""
    import cv2
    img_np = np.array(pil_img.convert("L"))   # RGB → greyscale
    return preprocess(img_np, Model.imgSize)

# ── Inference loop ───────────────────────────────────────────────
all_preds, all_gts = [], []
cer_sum = wer_sum = 0.0
errors = 0

for start in tqdm(range(0, total, BATCH_SIZE)):
    batch_items = eval_data[start : start + BATCH_SIZE]
    images  = batch_items["image"]
    gt_texts = batch_items["text"]

    # Preprocess images
    try:
        imgs_proc = [pil_to_model_input(img) for img in images]
    except Exception as e:
        errors += len(images)
        continue

    # Run inference
    try:
        preds = model.inferBatch(_Batch(imgs_proc))
    except Exception as e:
        errors += len(images)
        continue

    for pred, gt in zip(preds, gt_texts):
        pred = pred.strip()
        gt   = gt.strip()
        all_preds.append(pred)
        all_gts.append(gt)

        # Character Error Rate
        cer_sum += editdistance.eval(pred, gt) / max(len(gt), 1)
        # Word Error Rate
        wer_sum += editdistance.eval(pred.split(), gt.split()) / max(len(gt.split()), 1)

n = len(all_preds)
cer = cer_sum / n * 100
wer = wer_sum / n * 100
exact = sum(p == g for p, g in zip(all_preds, all_gts)) / n * 100

# ── Results ──────────────────────────────────────────────────────
print(f"\n{'='*55}")
print(f"  Results on '{SPLIT}' ({n} samples evaluated)")
print(f"{'='*55}")
print(f"  CER  (Character Error Rate) : {cer:.2f}%")
print(f"  WER  (Word Error Rate)      : {wer:.2f}%")
print(f"  Exact Match Accuracy        : {exact:.2f}%")
if errors:
    print(f"  Skipped (errors)            : {errors}")
print(f"{'='*55}")

# ── Sample predictions ───────────────────────────────────────────
print(f"\n{'─'*55}")
print("  Sample predictions (first 10):")
print(f"{'─'*55}")
for i in range(min(10, n)):
    match = "✅" if all_preds[i] == all_gts[i] else "❌"
    print(f"  {match} GT  : {all_gts[i]}")
    print(f"     PRED: {all_preds[i]}")
    print()

# sanity check on one image
import matplotlib.pyplot as plt
sample = dataset["test"][0]
proc   = pil_to_model_input(sample["image"])
print("processed shape:", proc.shape)   # should be (H, W, 1)
print("GT:", sample["text"])
print("PRED:", recognize_from_pil(sample["image"]) if False else model.inferBatch(_Batch([proc]))[0])
plt.imshow(proc[:,:,0], cmap="gray"); plt.title(sample["text"]); plt.show()

# ── FIXED EVALUATION CELL v4 ─────────────────────────────────────
import numpy as np
import editdistance
from tqdm.auto import tqdm

SPLIT      = "test"
MAX_ITEMS  = None
BATCH_SIZE = 16

eval_data = dataset[SPLIT]
if MAX_ITEMS:
    eval_data = eval_data.select(range(MAX_ITEMS))

total = len(eval_data)
print(f"Evaluating on {total} samples from '{SPLIT}' split...\n")

# inferBatch returns (list_of_preds, something_else)
# → take index [0] to get predictions, then each pred is a list → take [0] again
class _Batch:
    def __init__(self, imgs): self.imgs = imgs

def run_batch(imgs_proc):
    result = model.inferBatch(_Batch(imgs_proc))
    preds  = result[0]                          # unpack tuple → list of preds
    return [p[0].strip() if isinstance(p, list) else p.strip() for p in preds]

# ── Inference loop ───────────────────────────────────────────────
all_preds, all_gts = [], []
cer_sum = wer_sum = 0.0
exact_count = 0

for start in tqdm(range(0, total, BATCH_SIZE)):
    batch_items = eval_data[start : start + BATCH_SIZE]
    imgs_proc   = [preprocess(np.array(img.convert("L")), Model.imgSize)
                   for img in batch_items["image"]]
    preds       = run_batch(imgs_proc)

    for pred, gt in zip(preds, batch_items["text"]):
        gt = gt.strip()
        all_preds.append(pred)
        all_gts.append(gt)
        cer_sum += editdistance.eval(pred, gt)           / max(len(gt), 1)
        wer_sum += editdistance.eval(pred.split(), gt.split()) / max(len(gt.split()), 1)
        if pred == gt:
            exact_count += 1

n = len(all_preds)

# ── Metrics ──────────────────────────────────────────────────────
cer   = cer_sum     / n * 100
wer   = wer_sum     / n * 100
exact = exact_count / n * 100
ser   = 100 - exact

print(f"\n{'='*58}")
print(f"  Results on '{SPLIT}' split  ({n} samples)")
print(f"{'='*58}")
print(f"  CER  (Character Error Rate) : {cer:.2f}%")
print(f"  WER  (Word Error Rate)      : {wer:.2f}%")
print(f"  SER  (Sentence Error Rate)  : {ser:.2f}%")
print(f"  Exact Match Accuracy        : {exact:.2f}%")
print(f"{'='*58}")

# ── Sample predictions ───────────────────────────────────────────
print(f"\n  First 10 predictions:\n{'─'*58}")
for i in range(min(10, n)):
    match = "✅" if all_preds[i] == all_gts[i] else "❌"
    cer_i = editdistance.eval(all_preds[i], all_gts[i]) / max(len(all_gts[i]), 1) * 100
    print(f"  {match} GT  : {all_gts[i]}")
    print(f"       PRED : {all_preds[i]}")
    print(f"       CER  : {cer_i:.1f}%\n")

# ── CER distribution ─────────────────────────────────────────────
per_cer = [editdistance.eval(p,g)/max(len(g),1)*100 for p,g in zip(all_preds,all_gts)]
bins    = [0, 5, 10, 20, 50, 101]
print(f"  CER bucket distribution:")
print(f"  {'Range':>12}  {'Count':>7}  {'%':>7}")
print(f"  {'─'*32}")
for lo, hi in zip(bins, bins[1:]):
    c = sum(lo <= x < hi for x in per_cer)
    print(f"  {lo:>5}–{hi-1:<4}%   {c:>7}   {c/n*100:>5.1f}%")

# ── BIAS + FULL DISTRIBUTION ANALYSIS + IMAGE DISPLAY ────────────
import pandas as pd
import numpy as np
import editdistance
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

# ── Load Devanagari font for matplotlib ──────────────────────────
!fc-list | grep -i devanagari | head -1
FONT_PATH = "/usr/share/fonts/truetype/noto/NotoSansDevanagari-Regular.ttf"
font_prop = fm.FontProperties(fname=FONT_PATH)

def set_hindi_font():
    fm.fontManager.addfont(FONT_PATH)
    plt.rcParams["font.family"] = fm.FontProperties(fname=FONT_PATH).get_name()

set_hindi_font()

# ── Build results dataframe ──────────────────────────────────────
records = []
for i, (pred, gt) in enumerate(zip(all_preds, all_gts)):
    item   = eval_data[i]
    gt     = gt.strip()
    chars  = len(gt)
    words  = len(gt.split())
    cer_i  = editdistance.eval(pred, gt)                   / max(chars, 1) * 100
    wer_i  = editdistance.eval(pred.split(), gt.split())   / max(words, 1) * 100
    records.append({
        "idx":       i,
        "pred":      pred,
        "gt":        gt,
        "font":      item.get("font_file",  "unknown"),
        "font_size": item.get("font_size",  0),
        "word_count":item.get("word_count", words),
        "cer":       cer_i,
        "wer":       wer_i,
        "exact":     int(pred == gt),
        "ser":       int(pred != gt),
    })

df = pd.DataFrame(records)

# ── Helper: show images with GT + PRED ──────────────────────────
def show_samples(indices, title="Samples"):
    """Display images with GT / PRED labels for a list of dataset indices."""
    n = len(indices)
    if n == 0:
        print("  (no samples to show)")
        return
    fig, axes = plt.subplots(n, 1, figsize=(14, 2.4 * n))
    if n == 1:
        axes = [axes]
    for ax, idx in zip(axes, indices):
        row  = df.iloc[idx]
        img  = eval_data[int(row.idx)]["image"]
        ax.imshow(img, cmap="gray", aspect="auto")
        ax.axis("off")
        color = "green" if row.exact else "red"
        label = (f"GT  : {row.gt}\n"
                 f"PRED: {row.pred}\n"
                 f"CER : {row.cer:.1f}%  |  font: {row.font}  |  size: {row.font_size}")
        ax.set_title(label, fontproperties=font_prop, fontsize=9,
                     loc="left", color=color, pad=4)
    plt.suptitle(title, fontsize=11, fontweight="bold", y=1.01)
    plt.tight_layout()
    plt.show()

# ── 1. WER distribution ──────────────────────────────────────────
print("=" * 58)
print("  WER bucket distribution:")
print(f"  {'Range':>10}  {'Count':>7}  {'%':>7}")
print(f"  {'─'*32}")
for lo, hi in zip([0,5,10,20,50], [5,10,20,50,101]):
    c = ((df.wer >= lo) & (df.wer < hi)).sum()
    print(f"  {lo:>4}–{hi-1:<4}%   {c:>7}   {c/len(df)*100:>5.1f}%")

# ── 2. SER / CER by sentence length ─────────────────────────────
print(f"\n  SER by sentence length:")
print(f"  {'Words':>8}  {'Samples':>8}  {'SER%':>8}  {'CER%':>8}")
print(f"  {'─'*40}")
df["length_bin"] = pd.cut(df.word_count,
                           bins=[0,3,6,9,12,50],
                           labels=["1–3","4–6","7–9","10–12","13+"])
length_groups = df.groupby("length_bin", observed=True)
for grp, sub in length_groups:
    print(f"  {str(grp):>8}  {len(sub):>8}  "
          f"{sub.ser.mean()*100:>7.1f}%  {sub.cer.mean():>7.2f}%")

# worst 5 per length bucket — show images
print("\n  ── Worst samples by sentence length ──")
for grp, sub in length_groups:
    worst_idx = sub.nlargest(min(3, len(sub)), "cer").index.tolist()
    show_samples(worst_idx, title=f"Worst CER — word count: {grp}")

# ── 3. SER / CER by font ─────────────────────────────────────────
print(f"\n  SER by font file:")
print(f"  {'Font':>35}  {'Samples':>8}  {'SER%':>8}  {'CER%':>8}")
print(f"  {'─'*66}")
font_stats = (df.groupby("font")
                .agg(samples=("ser","count"),
                     ser_pct=("ser","mean"),
                     cer_avg=("cer","mean"))
                .sort_values("ser_pct", ascending=False))
for font, row in font_stats.iterrows():
    print(f"  {font:>35}  {int(row.samples):>8}  "
          f"{row.ser_pct*100:>7.1f}%  {row.cer_avg:>7.2f}%")

# worst 3 images per font with SER > 0
print("\n  ── Worst samples per font ──")
for font, sub in df[df.ser == 1].groupby("font"):
    worst_idx = sub.nlargest(min(3, len(sub)), "cer").index.tolist()
    show_samples(worst_idx, title=f"Font errors: {font}")

# ── 4. SER / CER by font size ────────────────────────────────────
print(f"\n  SER by font size:")
print(f"  {'Size':>8}  {'Samples':>8}  {'SER%':>8}  {'CER%':>8}")
print(f"  {'─'*40}")
df["size_bin"] = pd.cut(df.font_size,
                         bins=[0,20,30,40,50,200],
                         labels=["≤20","21–30","31–40","41–50","51+"])
for grp, sub in df.groupby("size_bin", observed=True):
    print(f"  {str(grp):>8}  {len(sub):>8}  "
          f"{sub.ser.mean()*100:>7.1f}%  {sub.cer.mean():>7.2f}%")

# worst 3 by font size
print("\n  ── Worst samples by font size ──")
for grp, sub in df.groupby("size_bin", observed=True):
    worst_idx = sub[sub.ser==1].nlargest(min(3, len(sub)), "cer").index.tolist()
    if worst_idx:
        show_samples(worst_idx, title=f"Worst CER — font size: {grp}")

# ── 5. Overall worst predictions ─────────────────────────────────
print(f"\n  Top 10 worst predictions overall:")
worst_overall = df.nlargest(10, "cer").index.tolist()
show_samples(worst_overall, title="Top 10 worst predictions (by CER)")

import subprocess
result = subprocess.run(["fc-list", "--format=%{file}\n"], capture_output=True, text=True)
deva_fonts = [l for l in result.stdout.splitlines() if "devanagari" in l.lower() or "Devanagari" in l]
print("Found Devanagari fonts:")
for f in deva_fonts:
    print(" ", f)

import subprocess, os

# Auto-detect any available Devanagari font
result = subprocess.run(["fc-list", "--format=%{file}\n"], capture_output=True, text=True)
deva_fonts = [l.strip() for l in result.stdout.splitlines()
              if ("devanagari" in l.lower() or "Devanagari" in l) and l.strip().endswith(".ttf")]

if not deva_fonts:
    # fallback: install and retry
    os.system("apt-get -qq install -y fonts-noto-core fonts-lohit-deva")
    result = subprocess.run(["fc-list", "--format=%{file}\n"], capture_output=True, text=True)
    deva_fonts = [l.strip() for l in result.stdout.splitlines()
                  if ("devanagari" in l.lower() or "Devanagari" in l) and l.strip().endswith(".ttf")]

FONT_PATH = deva_fonts[0]
print(f"✅ Using font: {FONT_PATH}")

# ── FIXED BIAS + DISTRIBUTION ANALYSIS (no font warnings) ────────
import warnings
warnings.filterwarnings("ignore")   # suppress all remaining glyph warnings

import pandas as pd
import numpy as np
import editdistance
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

# ── Font: load but DO NOT set globally ───────────────────────────
FONT_PATH = "/usr/share/fonts/truetype/noto/NotoSansDevanagari-Bold.ttf"
hindi_fp  = fm.FontProperties(fname=FONT_PATH)   # only for Hindi strings

# ── Build results dataframe ──────────────────────────────────────
records = []
for i, (pred, gt) in enumerate(zip(all_preds, all_gts)):
    item  = eval_data[i]
    gt    = gt.strip()
    chars = len(gt)
    words = len(gt.split())
    cer_i = editdistance.eval(pred, gt)                   / max(chars, 1) * 100
    wer_i = editdistance.eval(pred.split(), gt.split())   / max(words, 1) * 100
    records.append({
        "idx":       i,
        "pred":      pred,
        "gt":        gt,
        "font":      item.get("font_file",  "unknown"),
        "font_size": item.get("font_size",  0),
        "word_count":item.get("word_count", words),
        "cer":       cer_i,
        "wer":       wer_i,
        "exact":     int(pred == gt),
        "ser":       int(pred != gt),
    })
df = pd.DataFrame(records)

# ── Helper: show images with GT / PRED annotations ───────────────
def show_samples(indices, title="Samples"):
    n = len(indices)
    if n == 0:
        print("  (no samples to show)")
        return

    fig, axes = plt.subplots(n, 1, figsize=(14, 3.2 * n))
    if n == 1:
        axes = [axes]
    fig.suptitle(title, fontsize=11, fontweight="bold")   # ASCII title — default font

    for ax, idx in zip(axes, indices):
        row = df.iloc[idx]
        img = eval_data[int(row.idx)]["image"]
        ax.imshow(img, aspect="auto")
        ax.axis("off")

        color = "#1a7a1a" if row.exact else "#b22222"

        # ── Latin metadata above image using default font ─────────
        ax.text(0, -8,
                f"CER: {row.cer:.1f}%  |  font: {row.font}  |  size: {row.font_size}",
                transform=ax.transData, fontsize=8,
                color=color, va="bottom")

        # ── Hindi GT & PRED below image using Devanagari font ─────
        img_h = np.array(img).shape[0]
        ax.text(0, img_h + 4,
                f"GT:   {row.gt}",
                transform=ax.transData,
                fontproperties=hindi_fp, fontsize=9,
                color="#1a7a1a", va="top")
        ax.text(0, img_h + 22,
                f"PRED: {row.pred}",
                transform=ax.transData,
                fontproperties=hindi_fp, fontsize=9,
                color=color, va="top")

    plt.tight_layout()
    plt.show()

# ── 1. WER distribution ──────────────────────────────────────────
print("=" * 55)
print("  WER bucket distribution:")
print(f"  {'Range':>10}  {'Count':>7}  {'%':>7}")
print(f"  {'─'*32}")
for lo, hi in zip([0,5,10,20,50],[5,10,20,50,101]):
    c = ((df.wer >= lo) & (df.wer < hi)).sum()
    print(f"  {lo:>4}–{hi-1:<4}%   {c:>7}   {c/len(df)*100:>5.1f}%")

# ── 2. SER by sentence length ────────────────────────────────────
print(f"\n  SER by sentence length:")
print(f"  {'Words':>8}  {'Samples':>8}  {'SER%':>8}  {'CER%':>8}")
print(f"  {'─'*40}")
df["length_bin"] = pd.cut(df.word_count,
                           bins=[0,3,6,9,12,50],
                           labels=["1-3","4-6","7-9","10-12","13+"])
length_groups = df.groupby("length_bin", observed=True)
for grp, sub in length_groups:
    print(f"  {str(grp):>8}  {len(sub):>8}  "
          f"{sub.ser.mean()*100:>7.1f}%  {sub.cer.mean():>7.2f}%")

print("\n  -- Worst samples by sentence length --")
for grp, sub in length_groups:
    worst = sub.nlargest(min(3, len(sub)), "cer").index.tolist()
    show_samples(worst, title=f"Worst CER | word count: {grp}")

# ── 3. SER by font ───────────────────────────────────────────────
print(f"\n  SER by font file:")
print(f"  {'Font':>35}  {'Samples':>8}  {'SER%':>8}  {'CER%':>8}")
print(f"  {'─'*66}")
font_stats = (df.groupby("font")
                .agg(samples=("ser","count"),
                     ser_pct=("ser","mean"),
                     cer_avg=("cer","mean"))
                .sort_values("ser_pct", ascending=False))
for font, row in font_stats.iterrows():
    print(f"  {font:>35}  {int(row.samples):>8}  "
          f"{row.ser_pct*100:>7.1f}%  {row.cer_avg:>7.2f}%")

print("\n  -- Worst samples per font --")
for font, sub in df[df.ser == 1].groupby("font"):
    worst = sub.nlargest(min(3, len(sub)), "cer").index.tolist()
    show_samples(worst, title=f"Font: {font}")

# ── 4. SER by font size ──────────────────────────────────────────
print(f"\n  SER by font size:")
print(f"  {'Size':>8}  {'Samples':>8}  {'SER%':>8}  {'CER%':>8}")
print(f"  {'─'*40}")
df["size_bin"] = pd.cut(df.font_size,
                         bins=[0,20,30,40,50,200],
                         labels=["<=20","21-30","31-40","41-50","51+"])
for grp, sub in df.groupby("size_bin", observed=True):
    print(f"  {str(grp):>8}  {len(sub):>8}  "
          f"{sub.ser.mean()*100:>7.1f}%  {sub.cer.mean():>7.2f}%")

print("\n  -- Worst samples by font size --")
for grp, sub in df.groupby("size_bin", observed=True):
    worst = sub[sub.ser==1].nlargest(min(3, len(sub)), "cer").index.tolist()
    if worst:
        show_samples(worst, title=f"Font size: {grp}")

# ── 5. Top 10 worst overall ──────────────────────────────────────
print("\n  -- Top 10 worst predictions overall --")
show_samples(df.nlargest(10, "cer").index.tolist(),
             title="Top 10 worst predictions (by CER)")